package github

import (
	"context"
	"encoding/base64"
	"net/http"
	"net/http/httptest"
	"testing"
)

const bsd3WithPreamble = `Copyright 2008 Google Inc.  All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are
met:

    * Redistributions of source code must retain the above copyright
notice, this list of conditions and the following disclaimer.
    * Neither the name of Google Inc. nor the names of its
contributors may be used to endorse or promote products derived from
this software without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
"AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES ARE DISCLAIMED.

Code generated by the Protocol Buffer compiler is owned by the owner
of the input file used when generating it.`

// githubBase64 mimics GitHub's line-wrapped base64 encoding.
func githubBase64(s string) string {
	enc := base64.StdEncoding.EncodeToString([]byte(s))
	var out []byte
	for i := 0; i < len(enc); i += 60 {
		end := i + 60
		if end > len(enc) {
			end = len(enc)
		}
		out = append(out, enc[i:end]...)
		out = append(out, '\n')
	}
	return string(out)
}

func TestFetchLicense_OtherClassifiedFromContent(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case "/repos/protocolbuffers/protobuf/license":
			w.Header().Set("Content-Type", "application/json")
			_, _ = w.Write([]byte(`{
				"license": {"key": "other", "name": "Other", "spdx_id": "NOASSERTION"},
				"encoding": "base64",
				"content": ` + jsonString(githubBase64(bsd3WithPreamble)) + `
			}`))
		case "/repos/acme/eula/license":
			w.Header().Set("Content-Type", "application/json")
			_, _ = w.Write([]byte(`{
				"license": {"key": "other", "name": "Other", "spdx_id": "NOASSERTION"},
				"encoding": "base64",
				"content": ` + jsonString(githubBase64("END-USER LICENSE AGREEMENT. This software is licensed, not sold. You may not reverse engineer it.")) + `
			}`))
		default:
			w.WriteHeader(http.StatusNotFound)
		}
	}))
	defer server.Close()

	r := newTestResolverWithServer(server)

	if got, err := r.fetchLicense(context.Background(), "protocolbuffers", "protobuf"); err != nil || got != "BSD-3-Clause" {
		t.Errorf("expected text classification to yield BSD-3-Clause, got %q (err %v)", got, err)
	}
	if got, err := r.fetchLicense(context.Background(), "acme", "eula"); err != nil || got != "" {
		t.Errorf("proprietary text must not be classified, got %q (err %v)", got, err)
	}
}

func TestDetectFromContent(t *testing.T) {
	if got := detectFromContent(githubBase64(bsd3WithPreamble), "base64"); got != "BSD-3-Clause" {
		t.Errorf("base64: got %q", got)
	}
	if got := detectFromContent("", "base64"); got != "" {
		t.Errorf("empty: got %q", got)
	}
	if got := detectFromContent("%%%not-base64%%%", "base64"); got != "" {
		t.Errorf("invalid base64: got %q", got)
	}
}

func jsonString(s string) string {
	b := make([]byte, 0, len(s)+2)
	b = append(b, '"')
	for i := 0; i < len(s); i++ {
		switch s[i] {
		case '\n':
			b = append(b, '\\', 'n')
		case '"':
			b = append(b, '\\', '"')
		case '\\':
			b = append(b, '\\', '\\')
		default:
			b = append(b, s[i])
		}
	}
	return string(append(b, '"'))
}
